repositories:
  - name: jetstack
    url: https://charts.jetstack.io
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.13.0
    values:
      - installCRDs: true
