apiVersion: v1
kind: Namespace
metadata:
  name: network-health-test
  labels:
    network-health-sidecar/enabled: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: network-health-webhook-available
  namespace: kube-system
spec:
  containers:
    - name: await
      image: curlimages/curl:7.78.0
      command:
        - sh
        - -c
      args:
        - |
          rm /tmp/available
          until curl -k --max-time 10 --fail https://network-health.kube-system.svc.cluster.local:9443/healthz; do
            echo "webhook not available yet"
            sleep 5
          done
          sleep 5
          touch /tmp/available
          sleep infinity
      readinessProbe:
        exec:
          command:
          - test
          - -f
          - /tmp/available
---
apiVersion: v1
kind: Pod
metadata:
  name: network-health-test-pod-port
  namespace: network-health-test
  labels:
    network-health-sidecar/port: "8181"
spec:
  containers:
    - name: example
      image: nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: network-health-test-pod-socket
  namespace: network-health-test
spec:
  containers:
    - name: example
      image: nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: network-health-test-pod-disabled
  namespace: network-health-test
  labels:
    network-health-sidecar/enabled: "false"
spec:
  containers:
    - name: example
      image: nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80
